### PR TITLE
Update common_requirements

### PR DESCRIPTION
**Pull request by satyatumati**
Includes bug fixes

Signed-off-by: Satya Tumati <satyavasanth@g.ucla.edu>

### CODE REVIEW

**Comment by gaikwadabhishek** [comment]
Hey @satyatumati ,
Thank you for your first contribution. Why do we need this bump in `pydantic`?

**Comment by gaikwadabhishek** [comment]
Your commit isn't signed. Please review https://github.com/NVIDIA/aistore/blob/main/CONTRIBUTING.md

**Comment by gaikwadabhishek** [comment]
Sounds good. Can you rebase and squash all 4 commits into 1. I will approve, merge and trigger a pipeline to deploy newer version of aistore python SDK

**Comment by satyatumati** [comment]
Created a new pr. This got messed up. https://github.com/NVIDIA/aistore/pull/166 Thanks

**Pull request closed without merging**
