### PR TITLE
Update common_requirements

### PR DESCRIPTION
**Pull request by satyatumati**
Signed-off-by: Satya Tumati <<satyavasanth@g.ucla.edu>>

### CODE REVIEW

**Comment by gaikwadabhishek** [comment]
your signed off message is not correct - 
`remote: GitLab: Commit message does not follow the pattern '^(.*\n)*Signed-off-by:.+<\b[\w\.-]+@[\w\.-]+\.\w{2,99}\b>'

which is giving issues in merging. Expected - `Signed-off-by: Satya Tumati <satyavasanth@g.ucla.edu>` (the `<>` are missing)

**Comment by satyatumati** [comment]
can you try now?

**Comment by gaikwadabhishek** [comment]
Same issue. 
Your signed-off part is still not matching the traditional signed-off in commits. I can amend that but it will create problems in verifying.  For reference (`<>` are still missing)
```
commit 51fcc718a4fe4f5dfb259378dfce43d94f49573e (HEAD -> github-satyatumati, satya/patch-2)
Author: Satya Vasanth Reddy <satyavasanth@g.ucla.edu>
Date:   Wed Feb 7 10:15:43 2024 -0800

    Update common_requirements
    
    Signed-off-by: Satya Tumati satyavasanth@g.ucla.edu

commit 264a54173d4c34b4eda618dff87fd124597176a2 (root/main, root/HEAD, main)
Author: Alex Aizman <alex.aizman@gmail.com>
Date:   Wed Feb 7 12:54:56 2024 -0500

    blob downloader (new)
    
    * part eight, prev. commit: 7f06d6e9e284dd
    
    Signed-off-by: Alex Aizman <alex.aizman@gmail.com>

```

**Comment by gaikwadabhishek** [comment]
I think you are changing the description of this PR. But the issue is in the commit message.

**Comment by satyatumati** [comment]
updated the comment. Thanks

**Pull request merged**
